Organizations:
  - &OrdererOrg
    Name: ordererMSP
    ID: ordererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ordererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ordererMSP.admin')"
    OrdererEndpoints:
      - orderer.example.com:7050

  - &SmartBankA
    Name: smartbankaMSP
    ID: smartbankaMSP
    MSPDir: crypto-config/peerOrganizations/smartbanka.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('smartbankaMSP.admin', 'smartbankaMSP.peer', 'smartbankaMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('smartbankaMSP.admin', 'smartbankaMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('smartbankaMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('smartbankaMSP.peer')"
    AnchorPeers:
      - Host: peer0.smartbanka.com
        Port: 7051

  - &SmartBankB
    Name: smartbankbMSP
    ID: smartbankbMSP
    MSPDir: crypto-config/peerOrganizations/smartbankb.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('smartbankbMSP.admin', 'smartbankbMSP.peer', 'smartbankbMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('smartbankbMSP.admin', 'smartbankbMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('smartbankbMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('smartbankbMSP.peer')"
    AnchorPeers:
      - Host: peer0.smartbankb.com
        Port: 8051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *SmartBankA
          - *SmartBankB

  TwoOrgsChannel:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *SmartBankA
        - *SmartBankB
      Capabilities:
        <<: *ApplicationCapabilities
